-- warehouse-service owns order_status (+ order read-model) and inventory.

CREATE TABLE IF NOT EXISTS wh_order (
    order_id VARCHAR(20) NOT NULL,
    user_id VARCHAR(25),
    email_id VARCHAR(120),
    locale VARCHAR(10),
    total_price DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_wh_order PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS wh_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR(20),
    item_id VARCHAR(10),
    product_id VARCHAR(10),
    category_id VARCHAR(10),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    CONSTRAINT pk_wh_line PRIMARY KEY (id)
);

-- NOTE: inventory table moved to inventory-service (DB-per-service). Warehouse
-- owns only order status + read-model now; fulfilment happens over JMS.

-- NOTE: no credential store here anymore. Admin logins are authenticated by
-- auth-service (the central IdP); warehouse-service only VERIFIES RS256 tokens.
