-- NOTE: catalog tables (category/product/item + _details) removed — catalog data
-- is owned by the catalog-service microservice (DB-per-service). The monolith
-- holds no catalog schema; it calls catalog-service over HTTP via the SDK.

-- NOTE: customer/app_user tables removed — customer data is owned by the
-- customer-service microservice (DB-per-service). The monolith holds no
-- customer schema; it calls customer-service over HTTP.

-- Order context (Phase 4) — redesigned from legacy CMP PurchaseOrder/LineItem/Manager tables.
CREATE TABLE IF NOT EXISTS purchase_order (
    order_id VARCHAR(20) NOT NULL,
    user_id VARCHAR(25),
    email_id VARCHAR(120),
    order_date TIMESTAMP,
    locale VARCHAR(10),
    total_price DECIMAL(12,2) NOT NULL,
    CONSTRAINT pk_purchase_order PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR(20),
    category_id VARCHAR(10),
    product_id VARCHAR(10),
    item_id VARCHAR(10),
    line_number VARCHAR(10),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    CONSTRAINT pk_line_item PRIMARY KEY (id)
);


