-- OPC owns order_status (+ order read-model). Inventory lives in inventory-service
-- (DB-per-service); admin credentials live in auth-service (the central IdP).

CREATE TABLE IF NOT EXISTS wh_order (
    order_id VARCHAR(20) NOT NULL,
    user_id VARCHAR(25),
    email_id VARCHAR(120),
    locale VARCHAR(10),
    total_price DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    -- order-received timestamp (legacy PurchaseOrder poDate); for date-range sales aggregation
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- ship-to contact info collected at checkout (legacy PurchaseOrder shipping address)
    ship_family_name VARCHAR(60),
    ship_given_name VARCHAR(60),
    ship_street1 VARCHAR(120),
    ship_street2 VARCHAR(120),
    ship_city VARCHAR(60),
    ship_state VARCHAR(40),
    ship_zip VARCHAR(20),
    ship_country VARCHAR(40),
    ship_telephone VARCHAR(40),
    ship_email VARCHAR(120),
    -- bill-to contact info collected at checkout (legacy PurchaseOrder billing address)
    bill_family_name VARCHAR(60),
    bill_given_name VARCHAR(60),
    bill_street1 VARCHAR(120),
    bill_street2 VARCHAR(120),
    bill_city VARCHAR(60),
    bill_state VARCHAR(40),
    bill_zip VARCHAR(20),
    bill_country VARCHAR(40),
    bill_telephone VARCHAR(40),
    bill_email VARCHAR(120),
    CONSTRAINT pk_wh_order PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS wh_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR(20),
    item_id VARCHAR(10),
    product_id VARCHAR(10),
    category_id VARCHAR(10),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    CONSTRAINT pk_wh_line PRIMARY KEY (id)
);
