-- Transactional outbox for OPC's outbound events (OrderApprovedEvent → ApprovedOrderQueue,
-- OrderStatusEvent → OrderStatusTopic). A row is inserted in the SAME transaction as the
-- order-status write (see OutboxWriter, called from ApprovalGateway/OrderStatusGateway), so
-- the event and the state change commit or roll back atomically — closing the crash window
-- of the old after-commit publish (a committed status change whose JMS send never happened,
-- or a published event whose transaction later rolled back).
--
-- A separate poller (OutboxRelay) publishes unsent rows and stamps published_at. Delivery is
-- at-least-once (a crash between broker-send and the published_at update re-sends on the next
-- poll); the frozen JSON payload carries a fixed EventMeta.eventId, so consumers dedup the
-- redelivery. Rows that keep failing park once attempts hits the relay's cap (poison messages).

CREATE TABLE IF NOT EXISTS outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- JMS destination name + kind, so the relay can rebuild the Destination without a lookup
    destination VARCHAR(60) NOT NULL,
    is_topic BOOLEAN NOT NULL,
    -- logical event type id (the JMS _type); the relay maps it back to the event class
    event_type VARCHAR(80) NOT NULL,
    -- the event serialized as JSON (same Jackson mapper the JMS converter uses)
    payload CLOB NOT NULL,
    -- the order this event is about (for tracing / operational queries); nullable defensively
    order_id VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    -- NULL until the relay has published it; set = delivered
    published_at TIMESTAMP,
    -- publish attempts; parked as a poison row once it hits the relay's max-attempts cap
    attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_outbox PRIMARY KEY (id)
);

-- The relay's hot path: oldest-first scan of the unpublished backlog.
CREATE INDEX IF NOT EXISTS ix_outbox_unpublished ON outbox (published_at, id);
